-- =========================================================================
-- PULSEPRO DATABASE MIGRATION SCHEMA FOR SUPABASE SQL EDITOR
-- =========================================================================
-- Copy and paste this script directly into your Supabase Dashboard SQL Editor:
-- https://supabase.com/dashboard/project/_/sql
-- Click "RUN" to instantly setup and seed all relational database tables!
-- =========================================================================

-- 1. Create Users Table (Tracks Athlete Profiles and Trainer Profiles)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL CHECK(role IN ('user', 'trainer')),
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  email TEXT,
  first_name TEXT,
  last_name TEXT,
  dob TEXT,
  address TEXT,
  tel_no TEXT,
  height REAL,
  weight REAL,
  age INTEGER,
  location TEXT,
  profile_pic TEXT
);

-- Enable Row Level Security (RLS) or leave public for development
ALTER TABLE users FORCE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read/write access during development" ON users FOR ALL USING (true) WITH CHECK (true);

-- 2. Create Messages Table (Tracks Active Trainer-Athlete Live Chat Sessions)
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id BIGINT NOT NULL,
  receiver_id BIGINT NOT NULL,
  message TEXT NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE messages FORCE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read/write access during development" ON messages FOR ALL USING (true) WITH CHECK (true);

-- 3. Create Diets Table (Tracks Daily Athlete Food Intake and Calories)
CREATE TABLE IF NOT EXISTS diets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  day TEXT NOT NULL,
  meal_type TEXT NOT NULL,
  items TEXT NOT NULL,
  calories INTEGER
);

ALTER TABLE diets FORCE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read/write access during development" ON diets FOR ALL USING (true) WITH CHECK (true);

-- 4. Create Exercises Table (Tracks Active Gym Workout Routines)
CREATE TABLE IF NOT EXISTS exercises (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  sets INTEGER NOT NULL,
  reps INTEGER NOT NULL,
  duration INTEGER
);

ALTER TABLE exercises FORCE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read/write access during development" ON exercises FOR ALL USING (true) WITH CHECK (true);

-- =========================================================================
-- SEED INITIAL SYSTEM DATA (Enables instantaneous one-tap login simulation)
-- =========================================================================

-- Seed Fitness Trainer Profile
INSERT INTO users (id, role, username, password, email, first_name, last_name, profile_pic)
VALUES (1, 'trainer', 'Trainer123', 'trainer123', 'trainer@pulsepro.com', 'John', 'Doe', 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=150')
ON CONFLICT (username) DO UPDATE SET role = EXCLUDED.role;

-- Seed Athlete/User "Yuvindu"
INSERT INTO users (id, role, username, password, email, first_name, last_name, dob, address, tel_no, height, weight, age, location, profile_pic)
VALUES (2, 'user', 'Yuvindu', 'password123', 'Yu.ccpa@hotmail.com', 'Yuvindu', 'Senanayake', '2003-07-14', 'Colombo, Sri Lanka', '0771234567', 172.0, 76.0, 23, 'Sri Lanka', 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150')
ON CONFLICT (username) DO UPDATE SET role = EXCLUDED.role;

-- Seed Initial Real-Time Messages Chat History
INSERT INTO messages (sender_id, receiver_id, message)
VALUES 
  (1, 2, 'Welcome to PulsePro on Supabase! I am John, your personal trainer.'),
  (2, 1, 'Hi John! Glad to connect on the cloud database. Let us start tracking BMI.'),
  (1, 2, 'Excellent! Since your weight is 76kg and height is 172cm, your BMI is 25.7 (Overweight). We will aim for a healthy weight goal.');

-- Seed Monday Meal Plan
INSERT INTO diets (user_id, day, meal_type, items, calories)
VALUES 
  (2, 'Monday', 'Breakfast', 'Oatmeal with bananas and honey, Egg whites', 350),
  (2, 'Monday', 'Lunch', 'Grilled chicken breast with brown rice and broccoli', 550),
  (2, 'Monday', 'Dinner', 'Baked salmon with sweet potato and steamed asparagus', 480),
  (2, 'Monday', 'Snack', 'Greek yogurt with mixed berries, Almonds', 200);

-- Seed Workout Exercises
INSERT INTO exercises (user_id, name, sets, reps, duration)
VALUES 
  (2, 'Treadmill Jogging', 1, 1, 30),
  (2, 'Dumbbell Bicep Curls', 3, 12, 15),
  (2, 'Push-Ups', 4, 15, 10),
  (2, 'Barbell Squats', 4, 10, 20);
